swagger: '2.0'
info:
  title: Learn/Code/Rate API
  description: Endpoints for the Learn/Code/Rate web application API. Educational resources will be associated with ratings and reviews.
  version: 1.0.0
schemes:
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  /resource:
    get:
      responses:
        '200':
          description: Returns an array of all educational resource objects.
    post:
      responses:
        '200':
          description: Adds new educational resource object.
  /resource/{resourceId}:
    get:
      parameters:
        - name: resourceId
          in: path
          required: true
          description: The ID of the educational resource.
          type: integer
      responses:
        '200':
          description: Returns educational resource based on {resourceId}.
  /rate:
    get:
      responses:
        '200':
          description: Returns an array of ratings matched to {resourceId}s.
  /rate/{resourceId}:
    post:
      description: Creates new rating for resource based on {resourceId}.
      parameters:
        - name: resourceId
          in: path
          required: true
          description: The ID of the educational resource.
          type: integer
      responses:
        '200':
          description: Adds new rating based on {resourceId}.
    put:
      description: Updates rating for given resource.
      parameters:
        - name: resourceId
          in: path
          required: true
          description: The ID of the educational resource.
          type: integer
      responses:
        '200':
          description: Updates rating for given resource based on {resourceId}.
